spring:
  docker.compose.enabled: false

  application:
    name: shiroforbes-2

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/shiroforbes2?sslmode=disable
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

shiroforbes.app:
  jwt:
    secret: c2hpcm9mb3JiZXMtand0LXNlY3JldC1rZXktZm9yLXNhbXBsZS1hcHBsaWNhdGlvbg== # TODO: move it into a secure vault
    jwtExpirationMs: 86400000
    refreshExpirationMs: 604800000
  google:
    serviceAccountKeyFile: "service-account-key.json"
  rating:
    spreadsheetId: "19fm18aFwdENQHXRu3ekG1GRJtiIe-k1-XCMgtMQXFSQ"
    students: "ShV!A2:E"
    admins: "Admins!A2:E"
    teachers: "Teachers!A2:E"
    camps:
      countryside: "GradesCont!A1:ZZZ"
      urban1: "GradesUrb1!A1:ZZZ"
      urban2: "GradesUrb2!A1:ZZZ"